In [19]:
#Importing necessary libraries and frameworks
import tensorflow as tf
import scipy as sc
import numpy as np
import time
import sklearn.preprocessing
from scipy.signal import butter,lfilter


In [20]:
#Defining a butterworth filtter bandpass
def butter_bandpass(lowcut,highcut,fs,order=5):
    #Nyquist rate fs=2*fm
    #fm=0.5*fs
    nyq=0.5*fs
    lowcut=lowcut/nyq
    highcut=highcut/nyq
    #b,a=numerator and denominator values of the IIR Filter
    b,a=butter(order,[low,high],btype='band')
    return b,a

In [21]:
#Defining one hot encoding
#This function is used to transfer one column label to one hot label
def one_hot(y_):
    #Function to encode output labels from number indexes
    #e.g [[5],[3],[0]] --> [[0,0,0,0,0,1],[0,0,0,1,0,0],[0,0,0,0,0,0]]
#     y_=y_.reshape((len(y_)))
    y_=np.array(y_)
    y_=y_.reshape(len(y_))
    n_values=np.max(y_)+1
    return np.eye(n_values)[np.array(y_,dtype=np.int32)]

In [22]:
#Checking
a1=[[5],[3],[2]]
a2=one_hot(a1)
print(a2)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [23]:
def butter_bandpass_filter(data,lowcut,highcut,fs,order=5):
    b,a=butter_bandpass(lowcut,highcut,fs,order=order)
    y=lfilter(b,a,data)
    return y
    

Defining some variables used to load and process the EEG Data
1. **len_sample** = Length of each sample ( in seconds )
2. **full**= total number of samples per subject 
3. **n_fea**=number of features ( EEG Channels )
4. **label0-label7** = Defines the labels for each sample

In [25]:
len_sample=1
full=7000
len_a=int(full/len_sample)
label0=np.zeros(len_a)
label1=np.ones(len_a)
label2=np.ones(len_a)*2
label3=np.ones(len_a)*3
label4=np.ones(len_a)*4
label5=np.ones(len_a)*5
label6=np.ones(len_a)*6
label7=np.ones(len_a)*7
label=np.hstack((label0,label1,label2,label3,label4,label5,label6,label7))
label=label.T
label.shape=(len(label),1)
print(label)

[[0.]
 [0.]
 [0.]
 ...
 [7.]
 [7.]
 [7.]]


In [27]:
time=time.process_time()

In [29]:
feature=sc.io.loadmat("EID-S.mat")
all=feature['eeg_close_8sub_1file']